/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GalgjePackage;

import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Kai
 */
public class Galgje extends javax.swing.JFrame {

    /**
     * Creates new form Galgje
     */
    public Galgje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new JButton();
        lblPlaatje2 = new JLabel();
        lblPlaatje1 = new JLabel();
        lblPlaatje3 = new JLabel();
        lblPlaatje4 = new JLabel();
        lblPlaatje5 = new JLabel();
        lblPlaatje6 = new JLabel();
        lblPlaatje7 = new JLabel();
        lblPlaatje8 = new JLabel();
        lblPlaatje9 = new JLabel();
        lblPlaatje10 = new JLabel();
        lblPlaatje11 = new JLabel();
        lblPlaatje12 = new JLabel();
        btnLetterU = new JButton();
        btnLetterA = new JButton();
        btnLetterB = new JButton();
        btnLetterC = new JButton();
        btnLetterD = new JButton();
        btnLetterE = new JButton();
        btnLetterF = new JButton();
        btnLetterG = new JButton();
        btnLetterH = new JButton();
        btnLetterI = new JButton();
        btnLetterJ = new JButton();
        btnLetterK = new JButton();
        btnLetterL = new JButton();
        btnLetterM = new JButton();
        btnLetterN = new JButton();
        btnLetterO = new JButton();
        btnLetterP = new JButton();
        btnLetterQ = new JButton();
        btnLetterR = new JButton();
        btnLetterS = new JButton();
        btnLetterT = new JButton();
        btnLetterZ = new JButton();
        btnLetterY = new JButton();
        btnLetterX = new JButton();
        btnLetterW = new JButton();
        btnLetterV = new JButton();
        lblLetterV = new JLabel();
        lblLetterI = new JLabel();
        lblLetterS = new JLabel();
        lblVraagteken1 = new JLabel();
        lblVraagteken2 = new JLabel();
        lblVraagteken3 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new AbsoluteLayout());

        btnStart.setText("Start");
        btnStart.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new AbsoluteConstraints(30, 40, -1, -1));

        lblPlaatje2.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje2.png")); // NOI18N
        getContentPane().add(lblPlaatje2, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje1.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje1.png")); // NOI18N
        getContentPane().add(lblPlaatje1, new AbsoluteConstraints(420, 190, -1, 300));

        lblPlaatje3.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje3.png")); // NOI18N
        getContentPane().add(lblPlaatje3, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje4.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje4.png")); // NOI18N
        getContentPane().add(lblPlaatje4, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje5.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje5.png")); // NOI18N
        getContentPane().add(lblPlaatje5, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje6.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje6.png")); // NOI18N
        getContentPane().add(lblPlaatje6, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje7.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje7.png")); // NOI18N
        getContentPane().add(lblPlaatje7, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje8.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje8.png")); // NOI18N
        getContentPane().add(lblPlaatje8, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje9.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje9.png")); // NOI18N
        getContentPane().add(lblPlaatje9, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje10.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje10.png")); // NOI18N
        getContentPane().add(lblPlaatje10, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje11.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje11.png")); // NOI18N
        getContentPane().add(lblPlaatje11, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje12.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje12.png")); // NOI18N
        getContentPane().add(lblPlaatje12, new AbsoluteConstraints(420, 140, -1, -1));

        btnLetterU.setText("U");
        getContentPane().add(btnLetterU, new AbsoluteConstraints(40, 320, -1, -1));

        btnLetterA.setText("A");
        btnLetterA.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLetterAActionPerformed(evt);
            }
        });
        getContentPane().add(btnLetterA, new AbsoluteConstraints(20, 260, -1, -1));

        btnLetterB.setText("B");
        getContentPane().add(btnLetterB, new AbsoluteConstraints(60, 260, -1, -1));

        btnLetterC.setText("C");
        getContentPane().add(btnLetterC, new AbsoluteConstraints(100, 260, -1, -1));

        btnLetterD.setText("D");
        getContentPane().add(btnLetterD, new AbsoluteConstraints(140, 260, -1, -1));

        btnLetterE.setText("E");
        getContentPane().add(btnLetterE, new AbsoluteConstraints(180, 260, -1, -1));

        btnLetterF.setText("F");
        btnLetterF.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLetterFActionPerformed(evt);
            }
        });
        getContentPane().add(btnLetterF, new AbsoluteConstraints(220, 260, -1, -1));

        btnLetterG.setText("G");
        getContentPane().add(btnLetterG, new AbsoluteConstraints(260, 260, -1, -1));

        btnLetterH.setText("H");
        getContentPane().add(btnLetterH, new AbsoluteConstraints(30, 280, -1, -1));

        btnLetterI.setText("I");
        getContentPane().add(btnLetterI, new AbsoluteConstraints(70, 280, -1, -1));

        btnLetterJ.setText("J");
        btnLetterJ.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLetterJActionPerformed(evt);
            }
        });
        getContentPane().add(btnLetterJ, new AbsoluteConstraints(110, 280, -1, -1));

        btnLetterK.setText("K");
        getContentPane().add(btnLetterK, new AbsoluteConstraints(150, 280, -1, -1));

        btnLetterL.setText("L");
        btnLetterL.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLetterLActionPerformed(evt);
            }
        });
        getContentPane().add(btnLetterL, new AbsoluteConstraints(190, 280, -1, -1));

        btnLetterM.setText("M");
        getContentPane().add(btnLetterM, new AbsoluteConstraints(230, 280, -1, -1));

        btnLetterN.setText("N");
        getContentPane().add(btnLetterN, new AbsoluteConstraints(20, 300, -1, -1));

        btnLetterO.setText("O");
        getContentPane().add(btnLetterO, new AbsoluteConstraints(60, 300, -1, -1));

        btnLetterP.setText("P");
        getContentPane().add(btnLetterP, new AbsoluteConstraints(100, 300, -1, -1));

        btnLetterQ.setText("Q");
        getContentPane().add(btnLetterQ, new AbsoluteConstraints(140, 300, -1, -1));

        btnLetterR.setText("R");
        getContentPane().add(btnLetterR, new AbsoluteConstraints(180, 300, -1, -1));

        btnLetterS.setText("S");
        btnLetterS.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLetterSActionPerformed(evt);
            }
        });
        getContentPane().add(btnLetterS, new AbsoluteConstraints(220, 300, -1, -1));

        btnLetterT.setText("T");
        getContentPane().add(btnLetterT, new AbsoluteConstraints(260, 300, -1, -1));

        btnLetterZ.setText("Z");
        getContentPane().add(btnLetterZ, new AbsoluteConstraints(240, 320, -1, -1));

        btnLetterY.setText("Y");
        getContentPane().add(btnLetterY, new AbsoluteConstraints(200, 320, -1, -1));

        btnLetterX.setText("X");
        getContentPane().add(btnLetterX, new AbsoluteConstraints(160, 320, -1, -1));

        btnLetterW.setText("W");
        getContentPane().add(btnLetterW, new AbsoluteConstraints(120, 320, -1, -1));

        btnLetterV.setText("V");
        btnLetterV.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLetterVActionPerformed(evt);
            }
        });
        getContentPane().add(btnLetterV, new AbsoluteConstraints(80, 320, -1, -1));

        lblLetterV.setIcon(new ImageIcon(getClass().getResource("/GalgjePackage/letterV.png"))); // NOI18N
        getContentPane().add(lblLetterV, new AbsoluteConstraints(90, 170, -1, -1));

        lblLetterI.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\letterI.png")); // NOI18N
        getContentPane().add(lblLetterI, new AbsoluteConstraints(180, 180, -1, -1));

        lblLetterS.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\letterS.png")); // NOI18N
        getContentPane().add(lblLetterS, new AbsoluteConstraints(260, 180, -1, -1));

        lblVraagteken1.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\Vraagteken.png")); // NOI18N
        getContentPane().add(lblVraagteken1, new AbsoluteConstraints(80, 150, -1, 90));

        lblVraagteken2.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\Vraagteken.png")); // NOI18N
        getContentPane().add(lblVraagteken2, new AbsoluteConstraints(160, 150, -1, -1));

        lblVraagteken3.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\Vraagteken.png")); // NOI18N
        getContentPane().add(lblVraagteken3, new AbsoluteConstraints(250, 150, -1, -1));

        setBounds(0, 0, 936, 515);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
       lblPlaatje1.setVisible(true);
       lblPlaatje2.setVisible(false);
       lblPlaatje3.setVisible(false);
       lblPlaatje4.setVisible(false);
       lblPlaatje5.setVisible(false);
       lblPlaatje6.setVisible(false);
       lblPlaatje7.setVisible(false);
       lblPlaatje8.setVisible(false);
       lblPlaatje9.setVisible(false);
       lblPlaatje10.setVisible(false);
       lblPlaatje11.setVisible(false);
       lblPlaatje12.setVisible(false);
       lblLetterV.setVisible(false);
       lblLetterI.setVisible(false);
       lblLetterS.setVisible(false);
       lblVraagteken1.setVisible(true);
       lblVraagteken2.setVisible(true);
       lblVraagteken3.setVisible(true);
       
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnLetterFActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLetterFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLetterFActionPerformed

    private void btnLetterLActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLetterLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLetterLActionPerformed

    private void btnLetterAActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLetterAActionPerformed
        
    }//GEN-LAST:event_btnLetterAActionPerformed

    private void btnLetterVActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLetterVActionPerformed
        // TODO add your handling code here:
        lblLetterV.setVisible(true);
        lblVraagteken1.setVisible(false);
    }//GEN-LAST:event_btnLetterVActionPerformed

    private void btnLetterJActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLetterJActionPerformed
        // TODO add your handling code here:
        lblLetterI.setVisible(true);
        lblVraagteken2.setVisible(false);
    }//GEN-LAST:event_btnLetterJActionPerformed

    private void btnLetterSActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLetterSActionPerformed
        // TODO add your handling code here:
        lblLetterS.setVisible(true);
        lblVraagteken3.setVisible(false);
    }//GEN-LAST:event_btnLetterSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Galgje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Galgje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Galgje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Galgje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Galgje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnLetterA;
    private JButton btnLetterB;
    private JButton btnLetterC;
    private JButton btnLetterD;
    private JButton btnLetterE;
    private JButton btnLetterF;
    private JButton btnLetterG;
    private JButton btnLetterH;
    private JButton btnLetterI;
    private JButton btnLetterJ;
    private JButton btnLetterK;
    private JButton btnLetterL;
    private JButton btnLetterM;
    private JButton btnLetterN;
    private JButton btnLetterO;
    private JButton btnLetterP;
    private JButton btnLetterQ;
    private JButton btnLetterR;
    private JButton btnLetterS;
    private JButton btnLetterT;
    private JButton btnLetterU;
    private JButton btnLetterV;
    private JButton btnLetterW;
    private JButton btnLetterX;
    private JButton btnLetterY;
    private JButton btnLetterZ;
    private JButton btnStart;
    private JLabel lblLetterI;
    private JLabel lblLetterS;
    private JLabel lblLetterV;
    private JLabel lblPlaatje1;
    private JLabel lblPlaatje10;
    private JLabel lblPlaatje11;
    private JLabel lblPlaatje12;
    private JLabel lblPlaatje2;
    private JLabel lblPlaatje3;
    private JLabel lblPlaatje4;
    private JLabel lblPlaatje5;
    private JLabel lblPlaatje6;
    private JLabel lblPlaatje7;
    private JLabel lblPlaatje8;
    private JLabel lblPlaatje9;
    private JLabel lblVraagteken1;
    private JLabel lblVraagteken2;
    private JLabel lblVraagteken3;
    // End of variables declaration//GEN-END:variables
}
