/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GalgjePackage;

import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Kai
 */
public class Galgje extends javax.swing.JFrame {

    /**
     * Creates new form Galgje
     */
    public Galgje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLetter = new JTextField();
        jLabel1 = new JLabel();
        btnStart = new JButton();
        txtLetter1 = new JTextField();
        txtLetter2 = new JTextField();
        txtLetter3 = new JTextField();
        btnRaad = new JButton();
        lblPlaatje2 = new JLabel();
        lblPlaatje1 = new JLabel();
        lblPlaatje3 = new JLabel();
        lblPlaatje4 = new JLabel();
        lblPlaatje5 = new JLabel();
        lblPlaatje6 = new JLabel();
        lblPlaatje7 = new JLabel();
        lblPlaatje8 = new JLabel();
        lblPlaatje9 = new JLabel();
        lblPlaatje10 = new JLabel();
        lblPlaatje11 = new JLabel();
        lblPlaatje12 = new JLabel();
        btnLetterU = new JButton();
        btnLetterA = new JButton();
        btnLetterB = new JButton();
        btnLetterC = new JButton();
        btnLetterD = new JButton();
        btnLetterE = new JButton();
        btnLetterF = new JButton();
        btnLetterG = new JButton();
        btnLetterH = new JButton();
        btnLetterI = new JButton();
        btnLetterJ = new JButton();
        btnLetterK = new JButton();
        btnLetterL = new JButton();
        btnLetterM = new JButton();
        btnLetterN = new JButton();
        btnLetterO = new JButton();
        btnLetterP = new JButton();
        btnLetterQ = new JButton();
        btnLetterR = new JButton();
        btnLetterS = new JButton();
        btnLetterT = new JButton();
        btnLetterZ = new JButton();
        btnLetterY = new JButton();
        btnLetterX = new JButton();
        btnLetterW = new JButton();
        btnLetterV = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new AbsoluteLayout());
        getContentPane().add(txtLetter, new AbsoluteConstraints(450, 40, 100, -1));

        jLabel1.setText("Letter:");
        getContentPane().add(jLabel1, new AbsoluteConstraints(390, 40, -1, -1));

        btnStart.setText("Start");
        btnStart.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new AbsoluteConstraints(30, 40, -1, -1));

        txtLetter1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtLetter1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLetter1, new AbsoluteConstraints(100, 180, 50, 40));

        txtLetter2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtLetter2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLetter2, new AbsoluteConstraints(180, 180, 50, 40));

        txtLetter3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtLetter3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLetter3, new AbsoluteConstraints(260, 180, 50, 40));

        btnRaad.setText("Raad");
        btnRaad.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnRaadActionPerformed(evt);
            }
        });
        getContentPane().add(btnRaad, new AbsoluteConstraints(620, 40, -1, -1));

        lblPlaatje2.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje2.png")); // NOI18N
        getContentPane().add(lblPlaatje2, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje1.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje1.png")); // NOI18N
        getContentPane().add(lblPlaatje1, new AbsoluteConstraints(420, 190, -1, 300));

        lblPlaatje3.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje3.png")); // NOI18N
        getContentPane().add(lblPlaatje3, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje4.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje4.png")); // NOI18N
        getContentPane().add(lblPlaatje4, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje5.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje5.png")); // NOI18N
        getContentPane().add(lblPlaatje5, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje6.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje6.png")); // NOI18N
        getContentPane().add(lblPlaatje6, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje7.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje7.png")); // NOI18N
        getContentPane().add(lblPlaatje7, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje8.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje8.png")); // NOI18N
        getContentPane().add(lblPlaatje8, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje9.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje9.png")); // NOI18N
        getContentPane().add(lblPlaatje9, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje10.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje10.png")); // NOI18N
        getContentPane().add(lblPlaatje10, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje11.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje11.png")); // NOI18N
        getContentPane().add(lblPlaatje11, new AbsoluteConstraints(420, 140, -1, -1));

        lblPlaatje12.setIcon(new ImageIcon("C:\\Users\\Kai\\Documents\\NetBeansProjects\\Galgje\\src\\GalgjePackage\\galgje12.png")); // NOI18N
        getContentPane().add(lblPlaatje12, new AbsoluteConstraints(420, 140, -1, -1));

        btnLetterU.setText("U");
        getContentPane().add(btnLetterU, new AbsoluteConstraints(40, 320, -1, -1));

        btnLetterA.setText("A");
        btnLetterA.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLetterAActionPerformed(evt);
            }
        });
        getContentPane().add(btnLetterA, new AbsoluteConstraints(20, 260, -1, -1));

        btnLetterB.setText("B");
        getContentPane().add(btnLetterB, new AbsoluteConstraints(60, 260, -1, -1));

        btnLetterC.setText("C");
        getContentPane().add(btnLetterC, new AbsoluteConstraints(100, 260, -1, -1));

        btnLetterD.setText("D");
        getContentPane().add(btnLetterD, new AbsoluteConstraints(140, 260, -1, -1));

        btnLetterE.setText("E");
        getContentPane().add(btnLetterE, new AbsoluteConstraints(180, 260, -1, -1));

        btnLetterF.setText("F");
        btnLetterF.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLetterFActionPerformed(evt);
            }
        });
        getContentPane().add(btnLetterF, new AbsoluteConstraints(220, 260, -1, -1));

        btnLetterG.setText("G");
        getContentPane().add(btnLetterG, new AbsoluteConstraints(260, 260, -1, -1));

        btnLetterH.setText("H");
        getContentPane().add(btnLetterH, new AbsoluteConstraints(30, 280, -1, -1));

        btnLetterI.setText("I");
        getContentPane().add(btnLetterI, new AbsoluteConstraints(70, 280, -1, -1));

        btnLetterJ.setText("J");
        getContentPane().add(btnLetterJ, new AbsoluteConstraints(110, 280, -1, -1));

        btnLetterK.setText("K");
        getContentPane().add(btnLetterK, new AbsoluteConstraints(150, 280, -1, -1));

        btnLetterL.setText("L");
        btnLetterL.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLetterLActionPerformed(evt);
            }
        });
        getContentPane().add(btnLetterL, new AbsoluteConstraints(190, 280, -1, -1));

        btnLetterM.setText("M");
        getContentPane().add(btnLetterM, new AbsoluteConstraints(230, 280, -1, -1));

        btnLetterN.setText("N");
        getContentPane().add(btnLetterN, new AbsoluteConstraints(20, 300, -1, -1));

        btnLetterO.setText("O");
        getContentPane().add(btnLetterO, new AbsoluteConstraints(60, 300, -1, -1));

        btnLetterP.setText("P");
        getContentPane().add(btnLetterP, new AbsoluteConstraints(100, 300, -1, -1));

        btnLetterQ.setText("Q");
        getContentPane().add(btnLetterQ, new AbsoluteConstraints(140, 300, -1, -1));

        btnLetterR.setText("R");
        getContentPane().add(btnLetterR, new AbsoluteConstraints(180, 300, -1, -1));

        btnLetterS.setText("S");
        getContentPane().add(btnLetterS, new AbsoluteConstraints(220, 300, -1, -1));

        btnLetterT.setText("T");
        getContentPane().add(btnLetterT, new AbsoluteConstraints(260, 300, -1, -1));

        btnLetterZ.setText("Z");
        getContentPane().add(btnLetterZ, new AbsoluteConstraints(240, 320, -1, -1));

        btnLetterY.setText("Y");
        getContentPane().add(btnLetterY, new AbsoluteConstraints(200, 320, -1, -1));

        btnLetterX.setText("X");
        getContentPane().add(btnLetterX, new AbsoluteConstraints(160, 320, -1, -1));

        btnLetterW.setText("W");
        getContentPane().add(btnLetterW, new AbsoluteConstraints(120, 320, -1, -1));

        btnLetterV.setText("V");
        getContentPane().add(btnLetterV, new AbsoluteConstraints(80, 320, -1, -1));

        setBounds(0, 0, 936, 515);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
       lblPlaatje1.setVisible(true);
       lblPlaatje2.setVisible(false);
       lblPlaatje3.setVisible(false);
       lblPlaatje4.setVisible(false);
       lblPlaatje5.setVisible(false);
       lblPlaatje6.setVisible(false);
       lblPlaatje7.setVisible(false);
       lblPlaatje8.setVisible(false);
       lblPlaatje9.setVisible(false);
       lblPlaatje10.setVisible(false);
       lblPlaatje11.setVisible(false);
       lblPlaatje12.setVisible(false);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnRaadActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnRaadActionPerformed
        // TODO add your handling code here:
         try
        
        
         
         if a=()
                 {setText ()   }
         else  a=() false
                 {showPlaatje}
                 
          if b=()
                 {setText ()   }
         else  b=() false
                 {showPlaatje}
                 
          if c=()
                 {setText ()   }
         else  c=() false
                 {showPlaatje}
          if d=()
                 {setText ()   }
         else  d=() false
                 {showPlaatje}
                 
          if e=()
                 {setText ()   }
         else  e=() false
                 {showPlaatje}
                 
          if f=()
                 {setText ()   }
         else  f=() false
                 {showPlaatje}
          if g=()
                 {setText ()   }
         else  g=() false
                 {showPlaatje}
                 
          if h=()
                 {setText ()   }
         else  h=() false
                 {showPlaatje}
                 
          if i=()
                 {setText ()   }
         else  i=() false
                 {showPlaatje}
          if j=()
                 {setText ()   }
         else  j=() false
                 {showPlaatje}
                 
          if k=()
                 {setText ()   }
         else  k=() false
                 {showPlaatje}
          if l=()
                 {setText ()   }
         else  l=() false
                 {showPlaatje}
                 
          if m=()
                 {setText ()   }
         else  m=() false
                 {showPlaatje}
                 
          if n=()
                 {setText ()   }
         else  n=() false
                 {showPlaatje}
                 
          if o=()
                 {setText ()   }
         else  o=() false
                 {showPlaatje}
                 
          if p=()
                 {setText ()   }
         else  p=() false
                 {showPlaatje}
                 
          if q=()
                 {setText ()   }
         else  q=() false
                 {showPlaatje}
          if r=()
                 {setText ()   }
         else  r=() false
                 {showPlaatje}
          if s=()
                 {setText ()   }
         else  s=() false
                 {showPlaatje}
          if t=()
                 {setText ()   }
         else  t=() false
                 {showPlaatje}
          if u=()
                 {setText ()   }
         else  u=() false
                 {showPlaatje}
          if v=()
                 {setText ()   }
         else  v=() false
                 {showPlaatje}
          if w=()
                 {setText ()   }
         else  w=() false
                 {showPlaatje}
          if x=()
                 {setText ()   }
         else  x=() false
                 {showPlaatje}
          if y=()
                 {setText ()   }
         else  y=() false
                 {showPlaatje}
          if z=()
                 {setText ()   }
         else  z=() false
                 {showPlaatje}
         
         
                 
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(Galgje.this, "FOUT");
        }
    }//GEN-LAST:event_btnRaadActionPerformed

    private void txtLetter1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtLetter1ActionPerformed
        // TODO add your handling code here:
        txtLetter1.getValue = (22);
    }//GEN-LAST:event_txtLetter1ActionPerformed

    private void txtLetter2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtLetter2ActionPerformed
        // TODO add your handling code here:
        getValue = (9);
    }//GEN-LAST:event_txtLetter2ActionPerformed

    private void txtLetter3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtLetter3ActionPerformed
        // TODO add your handling code here:
        getValue = 19;
    }//GEN-LAST:event_txtLetter3ActionPerformed

    private void btnLetterFActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLetterFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLetterFActionPerformed

    private void btnLetterLActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLetterLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLetterLActionPerformed

    private void btnLetterAActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLetterAActionPerformed
        // TODO add your handling code here:
        btnLetterA.getValue = (1); 
    }//GEN-LAST:event_btnLetterAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Galgje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Galgje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Galgje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Galgje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Galgje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnLetterA;
    private JButton btnLetterB;
    private JButton btnLetterC;
    private JButton btnLetterD;
    private JButton btnLetterE;
    private JButton btnLetterF;
    private JButton btnLetterG;
    private JButton btnLetterH;
    private JButton btnLetterI;
    private JButton btnLetterJ;
    private JButton btnLetterK;
    private JButton btnLetterL;
    private JButton btnLetterM;
    private JButton btnLetterN;
    private JButton btnLetterO;
    private JButton btnLetterP;
    private JButton btnLetterQ;
    private JButton btnLetterR;
    private JButton btnLetterS;
    private JButton btnLetterT;
    private JButton btnLetterU;
    private JButton btnLetterV;
    private JButton btnLetterW;
    private JButton btnLetterX;
    private JButton btnLetterY;
    private JButton btnLetterZ;
    private JButton btnRaad;
    private JButton btnStart;
    private JLabel jLabel1;
    private JLabel lblPlaatje1;
    private JLabel lblPlaatje10;
    private JLabel lblPlaatje11;
    private JLabel lblPlaatje12;
    private JLabel lblPlaatje2;
    private JLabel lblPlaatje3;
    private JLabel lblPlaatje4;
    private JLabel lblPlaatje5;
    private JLabel lblPlaatje6;
    private JLabel lblPlaatje7;
    private JLabel lblPlaatje8;
    private JLabel lblPlaatje9;
    private JTextField txtLetter;
    private JTextField txtLetter1;
    private JTextField txtLetter2;
    private JTextField txtLetter3;
    // End of variables declaration//GEN-END:variables
}
